version: '3.5'

services:
  greeter-service:
    image: greeter_service:latest
    ports:
      - 50051:50051 # The opening port
    environment:
      MICRO_SERVER_ADDRESS: ":50051" # Specify the Go-micro server port
      PARAMS: "--registry etcd --registry_address etcd:2379"
    networks:
      - greeter
    depends_on:
      - etcd # Start after Etcd service start

  greeter-api-service:
    image: greeter_api:latest
    ports:
      - 3000:3000
    environment:
      PARAMS: "--registry etcd --registry_address etcd:2379"
    networks:
      - greeter
    depends_on:
      - etcd

  docker container ls

    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - greeter

networks:
  greeter:
    driver: bridge